
version: '3.8'

services:
  autobot:
    build: .
    container_name: autobot
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - DATABASE_URL=sqlite:///data/autobot.db
      - JWT_SECRET=${JWT_SECRET:-default_secret_change_in_production}
      - ENABLE_DOCS=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  autobot-worker:
    build: .
    container_name: autobot-worker
    restart: unless-stopped
    command: python -m src.autobot.worker
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - DATABASE_URL=sqlite:///data/autobot.db
      - JWT_SECRET=${JWT_SECRET:-default_secret_change_in_production}
    depends_on:
      - autobot

  autobot-scheduler:
    build: .
    container_name: autobot-scheduler
    restart: unless-stopped
    command: python -m src.autobot.scheduler
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - DATABASE_URL=sqlite:///data/autobot.db
      - JWT_SECRET=${JWT_SECRET:-default_secret_change_in_production}
    depends_on:
      - autobot

networks:
  default:
    driver: bridge
