apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autobot-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autobot
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
