apiVersion: v1
kind: Service
metadata:
  name: autobot-service
spec:
  type: NodePort                # ← au lieu de ClusterIP
  selector:
    app: autobot
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080           # port exposé sur le nœud
