api_key: "${SUPERAGI_API_KEY}"
base_url: "https://api.superagi.com"
model: "gpt-4"
max_tokens: 4000
temperature: 0.7

agents:
  autobot_master:
    name: "AutobotMaster"
    description: "Agent orchestrateur principal pour AUTOBOT, pilotant tous les composants via une interface conversationnelle"
    tools:
      - predict_tool
      - backtest_tool
      - train_tool
      - ghosting_tool
    prompt: |
      Tu es AutobotMaster, l'agent orchestrateur principal pour AUTOBOT.
      Tu contrôles les modules suivants :
      - HFT (trading haute fréquence)
      - Backtest (test rétrospectif des stratégies de trading)
      - E-commerce (gestion des produits et commandes)
      - Monitoring (surveillance des performances et sécurité)
      
      Tu peux utiliser les commandes suivantes :
      - "run prediction" ou "prédire" - pour exécuter des prédictions de trading
      - "run backtest" ou "tester" - pour exécuter des backtests sur des stratégies
      - "run training" ou "entraîner" - pour lancer l'entraînement des modèles
      - "start ghosting" ou "démarrer N clones" - pour démarrer des instances fantômes
      
      Lorsqu'on te donne une commande en langage naturel, tu dois la traduire en action appropriée.

tools:
  predict_tool:
    name: "PredictionTool"
    description: "Outil pour exécuter des prédictions de trading"
    endpoint: "/predict"
    method: "GET"
    parameters: {}
    
  backtest_tool:
    name: "BacktestTool"
    description: "Outil pour exécuter des backtests sur des stratégies"
    endpoint: "/backtest"
    method: "POST"
    parameters:
      strategy: "string"
      symbol: "string"
      timeframe: "string"
      
  train_tool:
    name: "TrainingTool"
    description: "Outil pour entraîner des modèles de trading"
    endpoint: "/train"
    method: "POST"
    parameters: {}
    
  ghosting_tool:
    name: "GhostingTool"
    description: "Outil pour démarrer des instances fantômes (clones)"
    endpoint: "/ghosting/start"
    method: "POST"
    parameters:
      count: "integer"
      markets: "array"
      strategies: "array"
