"""Research and validation building blocks for AUTOBOT.

This package is intentionally isolated from runtime paper/live execution. It
provides deterministic components for historical research, replay, metrics and
validation before any strategy can be considered for promotion.
"""

__all__ = [
    "ExecutionCostConfig",
    "ExecutionCostModel",
    "FillRequest",
    "FillResult",
    "BacktestConfig",
    "BacktestDecision",
    "BacktestEngine",
    "BacktestResult",
    "BacktestSignal",
    "AttributionBucket",
    "DecisionTrace",
    "DecisionTraceAuditConfig",
    "DecisionTraceAuditReport",
    "DecisionTraceAuditSummary",
    "DatasetBuildConfig",
    "DatasetBuildResult",
    "DatasetTimeframeExport",
    "MatrixCellLossAttribution",
    "MatrixLossAttributionReport",
    "LossAttributionResult",
    "MarketBar",
    "MarketDataQualityReport",
    "MarketDataRepository",
    "MetricsEngine",
    "MetricsResult",
    "MatrixCellResult",
    "MatrixRunConfig",
    "MatrixRunResult",
    "RegistryRecommendationCriteria",
    "RegistryRecommendationReport",
    "RoundTripPnL",
    "SetupQualityBucket",
    "SetupQualityReport",
    "StrategyRegimeBucket",
    "StrategyRegimeBaselineBucket",
    "StrategyRegimeBaselineReport",
    "StrategyRegimeWalkForwardFold",
    "StrategyRegimeWalkForwardFoldBucket",
    "StrategyRegimeWalkForwardReport",
    "StrategyRegimeWalkForwardSummary",
    "StrategyRegimeReport",
    "RegimeBaselineResult",
    "GridResearchConfig",
    "GridResearchSignalGenerator",
    "MeanReversionResearchConfig",
    "MeanReversionResearchSignalGenerator",
    "ResearchStrategyInstance",
    "RuntimeStrategyBacktestAdapter",
    "StrategyRecommendation",
    "StrategyEvidence",
    "StrategyScorecardCriteria",
    "StrategyScorecardReport",
    "StrategyScorecardResult",
    "TradeJournal",
    "TradeRecord",
    "TradingSignalAdapter",
    "ValidationRunnerConfig",
    "ValidationRunnerResult",
    "TrendResearchConfig",
    "TrendResearchSignalGenerator",
    "WalkForwardConfig",
    "WalkForwardDecision",
    "WalkForwardFoldResult",
    "WalkForwardResult",
    "WalkForwardValidator",
    "analyze_trade_journal",
    "analyze_trade_losses",
    "analyze_setup_quality",
    "analyze_setup_quality_journal",
    "analyze_setup_quality_journals",
    "analyze_strategy_regime_journals",
    "analyze_strategy_regimes",
    "aggregate_samples_to_ohlcv",
    "audit_decision_traces",
    "build_dataset_from_state_db",
    "enrich_bars_with_regime_context",
    "evaluate_strategy_regime_walk_forward",
    "evaluate_strategy_regime_walk_forward_journals",
    "load_matrix_result",
    "load_strategy_regime_report",
    "parse_timeframe_seconds",
    "recommend_from_matrix",
    "render_loss_attribution_report",
    "render_matrix_loss_attribution_report",
    "render_setup_quality_report",
    "render_strategy_regime_report",
    "render_strategy_regime_baseline_report",
    "render_strategy_regime_walk_forward_report",
    "render_strategy_scorecard_report",
    "render_decision_trace_audit_report",
    "run_validation",
    "run_validation_matrix",
    "write_loss_attribution_report",
    "write_matrix_loss_attribution_report",
    "write_matrix_setup_quality_report",
    "write_matrix_strategy_regime_report",
    "write_setup_quality_report",
    "write_strategy_regime_report",
    "write_matrix_strategy_regime_baseline_report",
    "write_strategy_regime_baseline_report",
    "write_matrix_strategy_regime_walk_forward_report",
    "write_strategy_regime_walk_forward_report",
    "write_strategy_scorecard_report",
    "write_registry_recommendation_report",
    "write_decision_trace_audit_report",
    "score_matrix",
    "score_strategy",
]

_LAZY_EXPORTS = {
    "DatasetBuildConfig": ("dataset_builder", "DatasetBuildConfig"),
    "DatasetBuildResult": ("dataset_builder", "DatasetBuildResult"),
    "DatasetTimeframeExport": ("dataset_builder", "DatasetTimeframeExport"),
    "aggregate_samples_to_ohlcv": ("dataset_builder", "aggregate_samples_to_ohlcv"),
    "build_dataset_from_state_db": ("dataset_builder", "build_dataset_from_state_db"),
    "parse_timeframe_seconds": ("dataset_builder", "parse_timeframe_seconds"),
    "BacktestConfig": ("backtest_engine", "BacktestConfig"),
    "BacktestDecision": ("backtest_engine", "BacktestDecision"),
    "BacktestEngine": ("backtest_engine", "BacktestEngine"),
    "BacktestResult": ("backtest_engine", "BacktestResult"),
    "BacktestSignal": ("backtest_engine", "BacktestSignal"),
    "AttributionBucket": ("loss_attribution", "AttributionBucket"),
    "DecisionTrace": ("decision_trace_audit", "DecisionTrace"),
    "DecisionTraceAuditConfig": ("decision_trace_audit", "DecisionTraceAuditConfig"),
    "DecisionTraceAuditReport": ("decision_trace_audit", "DecisionTraceAuditReport"),
    "DecisionTraceAuditSummary": ("decision_trace_audit", "DecisionTraceAuditSummary"),
    "audit_decision_traces": ("decision_trace_audit", "audit_decision_traces"),
    "render_decision_trace_audit_report": ("decision_trace_audit", "render_decision_trace_audit_report"),
    "write_decision_trace_audit_report": ("decision_trace_audit", "write_decision_trace_audit_report"),
    "LossAttributionResult": ("loss_attribution", "LossAttributionResult"),
    "MatrixCellLossAttribution": ("loss_attribution", "MatrixCellLossAttribution"),
    "MatrixLossAttributionReport": ("loss_attribution", "MatrixLossAttributionReport"),
    "analyze_trade_journal": ("loss_attribution", "analyze_trade_journal"),
    "analyze_trade_losses": ("loss_attribution", "analyze_trade_losses"),
    "render_loss_attribution_report": ("loss_attribution", "render_loss_attribution_report"),
    "render_matrix_loss_attribution_report": ("loss_attribution", "render_matrix_loss_attribution_report"),
    "write_loss_attribution_report": ("loss_attribution", "write_loss_attribution_report"),
    "write_matrix_loss_attribution_report": ("loss_attribution", "write_matrix_loss_attribution_report"),
    "write_matrix_setup_quality_report": ("setup_quality", "write_matrix_setup_quality_report"),
    "SetupQualityBucket": ("setup_quality", "SetupQualityBucket"),
    "SetupQualityReport": ("setup_quality", "SetupQualityReport"),
    "analyze_setup_quality": ("setup_quality", "analyze_setup_quality"),
    "analyze_setup_quality_journal": ("setup_quality", "analyze_setup_quality_journal"),
    "analyze_setup_quality_journals": ("setup_quality", "analyze_setup_quality_journals"),
    "render_setup_quality_report": ("setup_quality", "render_setup_quality_report"),
    "write_setup_quality_report": ("setup_quality", "write_setup_quality_report"),
    "StrategyRegimeBucket": ("strategy_regime_report", "StrategyRegimeBucket"),
    "StrategyRegimeReport": ("strategy_regime_report", "StrategyRegimeReport"),
    "analyze_strategy_regimes": ("strategy_regime_report", "analyze_strategy_regimes"),
    "analyze_strategy_regime_journals": ("strategy_regime_report", "analyze_strategy_regime_journals"),
    "render_strategy_regime_report": ("strategy_regime_report", "render_strategy_regime_report"),
    "write_strategy_regime_report": ("strategy_regime_report", "write_strategy_regime_report"),
    "write_matrix_strategy_regime_report": ("strategy_regime_report", "write_matrix_strategy_regime_report"),
    "RegimeBaselineResult": ("strategy_regime_baselines", "RegimeBaselineResult"),
    "StrategyRegimeBaselineBucket": ("strategy_regime_baselines", "StrategyRegimeBaselineBucket"),
    "StrategyRegimeBaselineReport": ("strategy_regime_baselines", "StrategyRegimeBaselineReport"),
    "render_strategy_regime_baseline_report": (
        "strategy_regime_baselines",
        "render_strategy_regime_baseline_report",
    ),
    "write_matrix_strategy_regime_baseline_report": (
        "strategy_regime_baselines",
        "write_matrix_strategy_regime_baseline_report",
    ),
    "write_strategy_regime_baseline_report": (
        "strategy_regime_baselines",
        "write_strategy_regime_baseline_report",
    ),
    "StrategyRegimeWalkForwardFold": ("strategy_regime_walk_forward", "StrategyRegimeWalkForwardFold"),
    "StrategyRegimeWalkForwardFoldBucket": (
        "strategy_regime_walk_forward",
        "StrategyRegimeWalkForwardFoldBucket",
    ),
    "StrategyRegimeWalkForwardReport": ("strategy_regime_walk_forward", "StrategyRegimeWalkForwardReport"),
    "StrategyRegimeWalkForwardSummary": ("strategy_regime_walk_forward", "StrategyRegimeWalkForwardSummary"),
    "evaluate_strategy_regime_walk_forward": (
        "strategy_regime_walk_forward",
        "evaluate_strategy_regime_walk_forward",
    ),
    "evaluate_strategy_regime_walk_forward_journals": (
        "strategy_regime_walk_forward",
        "evaluate_strategy_regime_walk_forward_journals",
    ),
    "render_strategy_regime_walk_forward_report": (
        "strategy_regime_walk_forward",
        "render_strategy_regime_walk_forward_report",
    ),
    "write_matrix_strategy_regime_walk_forward_report": (
        "strategy_regime_walk_forward",
        "write_matrix_strategy_regime_walk_forward_report",
    ),
    "write_strategy_regime_walk_forward_report": (
        "strategy_regime_walk_forward",
        "write_strategy_regime_walk_forward_report",
    ),
    "ExecutionCostConfig": ("execution_cost_model", "ExecutionCostConfig"),
    "ExecutionCostModel": ("execution_cost_model", "ExecutionCostModel"),
    "FillRequest": ("execution_cost_model", "FillRequest"),
    "FillResult": ("execution_cost_model", "FillResult"),
    "RoundTripPnL": ("execution_cost_model", "RoundTripPnL"),
    "MarketBar": ("market_data_repository", "MarketBar"),
    "MarketDataQualityReport": ("market_data_repository", "MarketDataQualityReport"),
    "MarketDataRepository": ("market_data_repository", "MarketDataRepository"),
    "MetricsEngine": ("metrics_engine", "MetricsEngine"),
    "MetricsResult": ("metrics_engine", "MetricsResult"),
    "MatrixCellResult": ("validation_matrix", "MatrixCellResult"),
    "MatrixRunConfig": ("validation_matrix", "MatrixRunConfig"),
    "MatrixRunResult": ("validation_matrix", "MatrixRunResult"),
    "run_validation_matrix": ("validation_matrix", "run_validation_matrix"),
    "RegistryRecommendationCriteria": ("registry_recommendations", "RegistryRecommendationCriteria"),
    "RegistryRecommendationReport": ("registry_recommendations", "RegistryRecommendationReport"),
    "StrategyRecommendation": ("registry_recommendations", "StrategyRecommendation"),
    "StrategyEvidence": ("strategy_scorecard", "StrategyEvidence"),
    "StrategyScorecardCriteria": ("strategy_scorecard", "StrategyScorecardCriteria"),
    "StrategyScorecardReport": ("strategy_scorecard", "StrategyScorecardReport"),
    "StrategyScorecardResult": ("strategy_scorecard", "StrategyScorecardResult"),
    "score_matrix": ("strategy_scorecard", "score_matrix"),
    "score_strategy": ("strategy_scorecard", "score_strategy"),
    "render_strategy_scorecard_report": ("strategy_scorecard", "render_strategy_scorecard_report"),
    "write_strategy_scorecard_report": ("strategy_scorecard", "write_strategy_scorecard_report"),
    "load_matrix_result": ("registry_recommendations", "load_matrix_result"),
    "load_strategy_regime_report": ("strategy_regime_report", "load_strategy_regime_report"),
    "recommend_from_matrix": ("registry_recommendations", "recommend_from_matrix"),
    "write_registry_recommendation_report": (
        "registry_recommendations",
        "write_registry_recommendation_report",
    ),
    "GridResearchConfig": ("strategy_signal_generators", "GridResearchConfig"),
    "GridResearchSignalGenerator": ("strategy_signal_generators", "GridResearchSignalGenerator"),
    "MeanReversionResearchConfig": ("strategy_signal_generators", "MeanReversionResearchConfig"),
    "MeanReversionResearchSignalGenerator": (
        "strategy_signal_generators",
        "MeanReversionResearchSignalGenerator",
    ),
    "TrendResearchConfig": ("strategy_signal_generators", "TrendResearchConfig"),
    "TrendResearchSignalGenerator": ("strategy_signal_generators", "TrendResearchSignalGenerator"),
    "ResearchStrategyInstance": ("strategy_adapters", "ResearchStrategyInstance"),
    "RuntimeStrategyBacktestAdapter": ("strategy_adapters", "RuntimeStrategyBacktestAdapter"),
    "TradingSignalAdapter": ("strategy_adapters", "TradingSignalAdapter"),
    "TradeJournal": ("trade_journal", "TradeJournal"),
    "TradeRecord": ("trade_journal", "TradeRecord"),
    "ValidationRunnerConfig": ("validation_runner", "ValidationRunnerConfig"),
    "ValidationRunnerResult": ("validation_runner", "ValidationRunnerResult"),
    "run_validation": ("validation_runner", "run_validation"),
    "enrich_bars_with_regime_context": ("regime_context", "enrich_bars_with_regime_context"),
    "WalkForwardConfig": ("walk_forward", "WalkForwardConfig"),
    "WalkForwardDecision": ("walk_forward", "WalkForwardDecision"),
    "WalkForwardFoldResult": ("walk_forward", "WalkForwardFoldResult"),
    "WalkForwardResult": ("walk_forward", "WalkForwardResult"),
    "WalkForwardValidator": ("walk_forward", "WalkForwardValidator"),
}


def __getattr__(name):
    """Expose research helpers without importing every submodule eagerly."""

    if name not in _LAZY_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr_name = _LAZY_EXPORTS[name]
    from importlib import import_module

    value = getattr(import_module(f"{__name__}.{module_name}"), attr_name)
    globals()[name] = value
    return value
